### ISSUE TITLE
get error when doing custom transform

### ISSUE THREAD

**Issue by HeikoR** [btford/grunt-conventional-changelog#58]
I get the following error when I try and override the transform object.

section from grunt config:
```
    conventionalChangelog: {
      options: {
        changelogOpts: {
          // conventional-changelog options go here
          preset: 'angular',

          transform: through.obj(function(chunk, enc, cb) {
            console.log("custom transform called ... ");

            cb(null, chunk);
          }),

          append: true

```

error:

```
Fatal error: Uncaught, unspecified "error" event.
```

I've looked at the default transform object used in conventional-changelog index.js file, even copied it. But whenever I try and pass in transfrom override from grunt, then I get the above error.

Also verified that the trough2 package version is the same as used in conventional changelog code.

Any ideas ? Would be helpful to have an example/testcase on this.

----- snip stack trace -----
```
custom transform called ...
Fatal error: Uncaught, unspecified "error" event.
Error: Uncaught, unspecified "error" event.
    at Error (native)
    at Readable.EventEmitter.emit (events.js:87:13)
    at DestroyableTransform.<anonymous> (d:\Projects\.........\conventional-changelog\index.js:198:20)
```

From the stack trace it seems to break in conventional-changelog\index.js when 
```
      gitRawCommits(gitRawCommitsOpts)
        .on('error', function(err) {
          readable.emit('error', 'Error in git-raw-commits. ' + err);
        })
        .pipe(conventionalCommitsParser(parserOpts))
        .on('error', function(err) {
          // ******* BREAKS HERE WITH ERR: "no writecb in Transform class"
          readable.emit('error', 'Error in conventional-commits-parser. ' + err);
        })
        .pipe(options.transform)       // when I uncomment this, or remove override transform then all good
```

**Comment by HeikoR** [comment]
Resolved!

Wrapped the transform object in a self executing function.

```
          transform: 
            (function() {
              through.obj(function(chunk, enc, cb) {
                console.log("custom transform called ... ");

                cb(null, chunk);
              })
            }
          )(),
```
