### ISSUE TITLE
Installation fails on Windows 10

### ISSUE THREAD

**Issue by ghachey** [btford/grunt-conventional-changelog#63]
So for this project I need to work on Windows. Trying to install this resutls in the following. I have otheriwse no issues installing and using other npm packages including grunt plugins which we have been using as our build system.

```
>npm install --save-dev grunt-conventional-changelog

> buffertools@2.1.4 install c:\myproject\node_modules\buffertools
> node-gyp rebuild


c:\myproject\node_modules\buffertools>if not defined npm_config_node_gyp (node "C:\Users\user\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppBuild.targets(366,5): warning MSB8003: Could not fi
nd WindowsSDKDir variable from the registry.  TargetFrameworkVersion or PlatformToolset may be set to an invalid versio
n number. [c:\myproject\node_modules\buffertools\build\buffertools.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the file specified. [c:\myproject\node_modules\buffertools\build\buffertools.vcxproj]


gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd c:\myproject\node_modules\buffertools
gyp ERR! node -v v4.4.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN install:buffertools@2.1.4 buffertools@2.1.4 install: `node-gyp rebuild`
npm WARN install:buffertools@2.1.4 Exit status 1
nopt@2.0.0 node_modules\grunt-contrib-watch\node_modules\tiny-lr\node_modules\noptify\node_modules\nopt -> node_modules\nopt
npm WARN optional Skipping failed optional dependency /grunt-ts/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@0.3.8
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.12
npm WARN Pineapples@1.0.0 No repository field.
```

**Comment by stevemao** [comment]
I'm not using Windows. PR welcome. Ideally setting up a Windows CI would be appreciated 😄

**Comment by ghachey** [comment]
Well, I don't use windows either :) Only for this project, but will see if I can get around doing it
